### GET request to example server
PUT http://localhost:4000/patients/f60571a9-b481-47ce-b6ef-0155e9e7e0a6
Content-Type: application/json


{
  "address": "behind shriram tower,dabki road",
  "dateOfBirth": "2003-02-01",
  "email": "rugu@gmail.com",
  "id": "f60571a9-b481-47ce-b6ef-0155e9e7e0a6",
  "name": "rugvedkhumkar"
}
###